# Generated by Django 3.2.6 on 2021-08-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_alter_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default='False')),
                ('blogpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blogs.blogpost')),
            ],
        ),
    ]
