# Generated by Django 3.2.6 on 2021-08-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_post',
            name='blogpost',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blogs.blogpost'),
        ),
    ]
